.Dd February 6, 2018

.Dt KIKI 3

.Os GNU/Linux

.Sh NAME
.Nm kiki_save_buffer
.Nd save a device buffer to a file

.Sh SYNOPSIS
.Fd #include <kiki_api.h>
.Ft ssize_t
.Fo kiki_save_buffer
.Fa "kiki_buffer_handle_t *buffer"
.Fa "FILE *output"
.Fc

.Sh DESCRIPTION
The
.Fn kiki_save_buffer
function is in charge of dumping a device buffer entirely in a file.
The format in which the buffer is saved in the file is left implementation-defined, as long as the
.Fn kiki_load_buffer
function can read it back.


.Sh RETURN VALUES
In case of success, 0 is returned.

If dynamic memory allocation fails, a value of -2 is returned.

If the
.Fa output
parameter is invalid, a less-than-zero value should be returned.

Otherwise, the function should not fail in any other circumstance, even if the underlying kernel interface call(s) could.


.Va errno
is
.Va not
set accordingly.


.Sh ERRORS
.Fn kiki_save_buffer
should only fail if the passed argument
.Fa output
is not a valid opened FILE* or if dynamic memory allocation fails.

In any other circumstance, the function should not fail, even if an underlying kernel interface call may.


.Sh SEE ALSO
.Xr kiki_read_buffer 3 ,
.Xr kiki_load_buffer 3


.Sh HISTORY
An
.Fn kiki_save_buffer
function first appeared in 2018,
for the CS Games Operating Systems competition.
