
obj-m := kiki.o

kiki-y := \
module.o \
init.o \
deinit.o \
uevent.o \
fops.o \
open.o \
release.o \
read.o \
ioctl.o \
status.o \
state.o \
reset.o \
random_fail.o \
buffer_list.o \
buffer_selection.o \
correction_stats_struct.o \
ioctls/get_status.o \
ioctls/wait_proc_work.o \
ioctls/reqbuf.o \
ioctls/listbuf.o \
ioctls/countbuf.o \
ioctls/selbuf.o \
ioctls/clearbufs.o \
ioctls/do_not_call.o \
ioctls/fillbuf.o \
ioctls/dumpbuf.o \
ioctls/inspbuf.o \
ioctls/ioinfo.o \
ioctls/getstate.o \
ioctls/setstatelis.o \
ioctls/setstateans.o \
ioctls/reset_ioctl.o \
ioctls/correction_stats.o
